name: RLMathToolkit CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1 — checkout sources
    - uses: actions/checkout@v4

    # 2 — Python + Poetry cache
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: "poetry"          # speeds up subsequent runs

    # 3 — install Poetry
    - uses: snok/install-poetry@v1
      with:
        virtualenvs-in-project: true
        installer-parallel: true

    # 4 — install dependencies (deps first, then your package)
    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-ansi --no-root
        poetry install --no-interaction --no-ansi

    # 5 — lint
    - name: Lint with Ruff
      run: poetry run ruff check rlmathtoolkit tests

    # 6 — tests + coverage
    - name: Run unit tests
      run: poetry run pytest -q --cov=rlmathtoolkit --cov-report=term-missing
