name: RLMathToolkit CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1 — Check out source code
    - uses: actions/checkout@v4

    # 2 — Install Python 3.11
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    # 3 — Install Poetry
    - uses: snok/install-poetry@v1
      with:
        virtualenvs-in-project: true   # creates .venv in repo root
        installer-parallel: true

    # 4 — Restore Poetry / pip / venv cache
    - name: Restore cached virtual-env & wheels
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          ~/.cache/pip
          .venv
        key: ${{ runner.os }}-py311-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-py311-poetry-

    # 5 — Install dependencies
    #     • First: third-party only  (for better cache hits)
    #     • Second: your package itself
    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-ansi --no-root
        poetry install --no-interaction --no-ansi

    # 6 — Lint
    - name: Ruff lint
      run: poetry run ruff check rlmathtoolkit tests

    # 7 — Run tests
    - name: Pytest + coverage
      run: poetry run pytest -q --cov=rlmathtoolkit --cov-report=term-missing
